# Generated by Django 3.1.7 on 2021-05-28 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(blank=True, max_length=100, null=True)),
                ('topic', models.TextField(blank=True, max_length=100, null=True)),
                ('subject', models.TextField(blank=True, max_length=100, null=True)),
                ('pages', models.CharField(blank=True, max_length=5, null=True)),
                ('files', models.TextField(blank=True, max_length=10000, null=True)),
                ('cost', models.TextField(blank=True, max_length=10, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('posted_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('is_assigned', models.BooleanField(default=False)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('bidders', models.ManyToManyField(blank=True, related_name='project_bidders', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_posted_by', to=settings.AUTH_USER_MODEL)),
                ('winner_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_winner_bidder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreelanceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(auto_created=True, unique=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('order_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('order_placed_on', models.DateTimeField()),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinewriting.project')),
            ],
        ),
    ]
