# Generated by Django 3.1.7 on 2021-05-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinewriting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceorder',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
