# Generated by Django 3.1.7 on 2021-05-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinewriting', '0002_auto_20210529_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
