# Generated by Django 3.1.7 on 2021-05-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinewriting', '0006_auto_20210529_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
