# Generated by Django 3.1.7 on 2021-05-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinewriting', '0008_projectfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='files',
        ),
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_files', to='onlinewriting.ProjectFile'),
        ),
    ]
